export enum ErrorCodes {
  UNKNOWN = 'UNKNOWN',
  DELETED_USER = 'DELETED_USER',
  UNAUTHORIZED = 'UNAUTHORIZED',
  PRIVILEGE_ERROR = 'PRIVILEGE_ERROR',
}

export enum ApiErrorCodes {
  INVALID_CERTIFICATE_PIN = 'INVALID_CERTIFICATE_PIN',
  EXPIRED_CERTIFICATE = 'EXPIRED_CERTIFICATE',
  CERTIFICATE_ERROR = 'CERTIFICATE_ERROR',
}
